apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: device-plugin-modify-ds
  namespace: kube-system
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        component: gpushare-device-plugin
        app: gpushare
        name: device-plugin-modify-ds
    spec:
      hostNetwork: true
      nodeSelector:
        gpushare: "true"
      containers:
      - image: {{ .Values.modifyDevicePluginImage }}
        command:
        - /dp-modify/dp-modify.sh
        args:
        - --request-cpu
        - "0"
        name: gpushare
        # Make this pod as Guaranteed pod which will never be evicted because of node's resource consumption.
        securityContext:
          privileged: true
        volumeMounts:
          - name: k8s-host
            mountPath: /k8s-host
      volumes:
      - hostPath:
          path: /
          type: Directory
        name: k8s-host
